config/routes.rb
TeachboxNoit::Application.routes.draw do
  resources :quick_answers

  resources :quick_questions

  resources :comments_closed_group_posts

  resources :closed_group_posts

  resources :closed_groups

  resources :comments_course_posts

  resources :course_posts

  resources :courses

  resources :comments_open_group_posts

  resources :open_group_posts

  resources :open_groups

  root to: 'menu#index'
  devise_for :users

  devise_for :admin_users, ActiveAdmin::Devise.config
  ActiveAdmin.routes(self)

  resources :users

  resources :open_groups do
     post :join, :on => :collection
     post :like, :on => :collection
     post :like_post, :on => :collection
     post :like_comment, :on => :collection
  end

  resources :closed_groups do
     post :join, :on => :collection
     post :like, :on => :collection
     post :like_post, :on => :collection
  end
  
  resources :courses do
     post :join, :on => :collection
     post :like, :on => :collection
     post :like_post, :on => :collection
  end

end

app/models/admin_user.rb
class AdminUser < ActiveRecord::Base
  # Include default devise modules. Others available are:
  # :confirmable, :lockable, :timeoutable and :omniauthable
  devise :database_authenticatable, 
         :recoverable, :rememberable, :trackable, :validatable

  # Setup accessible (or protected) attributes for your model
  attr_accessible :email, :password, :password_confirmation, :remember_me
  # attr_accessible :title, :body
end

app/models/closed_group.rb
class ClosedGroup < ActiveRecord::Base
  attr_accessible :admin_id, :decription, :name

  has_many :user_closed_group
  has_many :closed_group_posts
  has_many :requests
end

app/models/closed_group_post.rb
class ClosedGroupPost < ActiveRecord::Base
  attr_accessible :closed_group_id, :content, :title, :user_id, :attach

  belongs_to :user
  belongs_to :closed_group

  has_many :likes_closed_group_posts
  has_many :comments_closed_group_posts
  has_attached_file :attach
end

app/models/course.rb
class Course < ActiveRecord::Base
  attr_accessible :description, :name, :user_id

  has_many :user_courses
  has_many :course_posts
end

app/models/course_post.rb
class CoursePost < ActiveRecord::Base
  attr_accessible :content, :course_id, :title, :user_id, :attach

  belongs_to :user
  belongs_to :course

  has_many :likes_course_posts
  has_many :comments_course_posts
  has_attached_file :attach
end

app/models/likes_closed_group.rb
class LikesClosedGroup < ActiveRecord::Base
  attr_accessible :closed_group_id, :user_id

  belongs_to :user
  belongs_to :closed_group
end

app/models/likes_course.rb
class LikesCourse < ActiveRecord::Base
  attr_accessible :course_id, :user_id

  belongs_to :user
  belongs_to :course
end

app/models/likes_course_post.rb
class LikesCoursePost < ActiveRecord::Base
  attr_accessible :course_post_id, :like_attribute, :user_id
  
  belongs_to :user
  belongs_to :course_post
end

app/models/likes_open_group.rb
class LikesOpenGroup < ActiveRecord::Base
  attr_accessible :open_group_id, :user_id

  belongs_to :user
  belongs_to :open_group
end

app/models/open_group.rb
class OpenGroup < ActiveRecord::Base
  attr_accessible :description, :name

  has_many :user_open_group
  has_many :open_group_posts
end

app/models/open_group_post.rb
class OpenGroupPost < ActiveRecord::Base
  attr_accessible :content, :open_group_id, :title, :user_id, :attach

  belongs_to :user
  belongs_to :open_group

  has_many :likes_open_group_posts
  has_many :comments_open_group_posts
  has_attached_file :attach
end

app/models/quick_answer.rb
class QuickAnswer < ActiveRecord::Base
  attr_accessible :answer, :quick_question_id, :user_id

  belongs_to :quick_question
  belongs_to :user
end

app/models/quick_question.rb
class QuickQuestion < ActiveRecord::Base
  attr_accessible :question, :user_id

  belongs_to :user
  has_many :quick_answers
end

app/models/request.rb
class Request < ActiveRecord::Base
  attr_accessible :closed_group_id, :user_id

  belongs_to :closed_group
  belongs_to :user
end

app/models/user.rb
class User < ActiveRecord::Base
  # Include default devise modules. Others available are:
  # :confirmable, :lockable, :timeoutable and :omniauthable
  devise :database_authenticatable, :registerable, :recoverable, :rememberable, :trackable, :validatable

  # Setup accessible (or protected) attributes for your model
  attr_accessible :email, :password, :password_confirmation, :remember_me
  attr_accessible :email, :name, :password, :attach, :pic
  validates :name, :presence => true    
  validates :email, :presence => true

  has_attached_file :pic, :styles => { :medium => "300x300>", :thumb => "100x100>" }
  has_attached_file :attach

  has_many :user_open_group
  has_many :open_group_posts
  has_many :likes_open_groups
  has_many :likes_open_group_posts
  has_many :comments_open_group_posts

  has_many :user_course
  has_many :course_posts
  has_many :likes_courses
  has_many :likes_course_posts
  has_many :comments_course_posts

  has_many :user_closed_group
  has_many :closed_group_posts
  has_many :likes_closed_group
  has_many :likes_closed_group_posts
  has_many :comments_closed_group_posts
end

app/models/user_closed_group.rb
class UserClosedGroup < ActiveRecord::Base
  attr_accessible :closed_group_id, :user_id

  belongs_to :closed_group
  belongs_to :user
end

app/models/user_course.rb
class UserCourse < ActiveRecord::Base
  attr_accessible :course_id, :user_id

  belongs_to :course
  belongs_to :user
end

app/models/user_open_group.rb
class UserOpenGroup < ActiveRecord::Base
  attr_accessible :open_group_id, :user_id

  belongs_to :open_group
  belongs_to :user
end

app/controllers/quick_answers_controller.rb
class QuickAnswersController < ApplicationController
  # GET /quick_answers
  # GET /quick_answers.json
  def index
    @quick_answers = QuickAnswer.all

    respond_to do |format|
      format.html # index.html.erb
      format.json { render json: @quick_answers }
    end
  end

  # GET /quick_answers/1
  # GET /quick_answers/1.json
  def show
    @quick_answer = QuickAnswer.find(params[:id])

    respond_to do |format|
      format.html # show.html.erb
      format.json { render json: @quick_answer }
    end
  end

  # GET /quick_answers/new
  # GET /quick_answers/new.json
  def new
    @quick_answer = QuickAnswer.new

    respond_to do |format|
      format.html # new.html.erb
      format.json { render json: @quick_answer }
    end
  end

  # GET /quick_answers/1/edit
  def edit
    @quick_answer = QuickAnswer.find(params[:id])
  end

  # POST /quick_answers
  # POST /quick_answers.json
  def create
    @quick_answer = QuickAnswer.new(params[:quick_answer])

    respond_to do |format|
      if @quick_answer.save
        format.html { redirect_to :back }
        format.json { render json: @quick_answer, status: :created, location: @quick_answer }
      else
        format.html { render action: "new" }
        format.json { render json: @quick_answer.errors, status: :unprocessable_entity }
      end
    end
  end

  # PUT /quick_answers/1
  # PUT /quick_answers/1.json
  def update
    @quick_answer = QuickAnswer.find(params[:id])

    respond_to do |format|
      if @quick_answer.update_attributes(params[:quick_answer])
        format.html { redirect_to @quick_answer, notice: 'Quick answer was successfully updated.' }
        format.json { head :no_content }
      else
        format.html { render action: "edit" }
        format.json { render json: @quick_answer.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /quick_answers/1
  # DELETE /quick_answers/1.json
  def destroy
    @quick_answer = QuickAnswer.find(params[:id])
    @quick_answer.destroy

    respond_to do |format|
      format.html { redirect_to quick_answers_url }
      format.json { head :no_content }
    end
  end
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/courses_helper.rb
module CoursesHelper
end

app/helpers/quick_answers_helper.rb
module QuickAnswersHelper
end

app/helpers/users_helper.rb
module UsersHelper
end

app/views/quick_answers/_form.html.erb
<%= form_for(@quick_answer) do |f| %>
  <% if @quick_answer.errors.any? %>
    <div id="error_explanation">
      <h2><%= pluralize(@quick_answer.errors.count, "error") %> prohibited this quick_answer from being saved:</h2>

      <ul>
      <% @quick_answer.errors.full_messages.each do |msg| %>
        <li><%= msg %></li>
      <% end %>
      </ul>
    </div>
  <% end %>

  <div class="field">
    <%= f.label :answer %><br />
    <%= f.text_area :answer %>
  </div>
  <div class="field">
    <%= f.label :user_id %><br />
    <%= f.number_field :user_id %>
  </div>
  <div class="field">
    <%= f.label :quick_question_id %><br />
    <%= f.number_field :quick_question_id %>
  </div>
  <div class="actions">
    <%= f.submit %>
  </div>
<% end %>

app/views/quick_answers/edit.html.erb
<h1>Editing quick_answer</h1>

<%= render 'form' %>

<%= link_to 'Show', @quick_answer %> |
<%= link_to 'Back', quick_answers_path %>

app/views/quick_answers/index.html.erb
<h1>Listing quick_answers</h1>

<table>
  <tr>
    <th>Answer</th>
    <th>User</th>
    <th>Quick question</th>
    <th></th>
    <th></th>
    <th></th>
  </tr>

<% @quick_answers.each do |quick_answer| %>
  <tr>
    <td><%= quick_answer.answer %></td>
    <td><%= quick_answer.user_id %></td>
    <td><%= quick_answer.quick_question_id %></td>
    <td><%= link_to 'Show', quick_answer %></td>
    <td><%= link_to 'Edit', edit_quick_answer_path(quick_answer) %></td>
    <td><%= link_to 'Destroy', quick_answer, method: :delete, data: { confirm: 'Are you sure?' } %></td>
  </tr>
<% end %>
</table>

<br />

<%= link_to 'New Quick answer', new_quick_answer_path %>

app/views/quick_answers/new.html.erb
<h1>New quick_answer</h1>

<%= render 'form' %>

<%= link_to 'Back', quick_answers_path %>

app/views/quick_answers/show.html.erb
<p id="notice"><%= notice %></p>

<p>
  <b>Answer:</b>
  <%= @quick_answer.answer %>
</p>

<p>
  <b>User:</b>
  <%= @quick_answer.user_id %>
</p>

<p>
  <b>Quick question:</b>
  <%= @quick_answer.quick_question_id %>
</p>


<%= link_to 'Edit', edit_quick_answer_path(@quick_answer) %> |
<%= link_to 'Back', quick_answers_path %>