config/routes.rb
TeachboxNoit::Application.routes.draw do
  resources :quick_answers

  resources :quick_questions

  resources :comments_closed_group_posts

  resources :closed_group_posts

  resources :closed_groups

  resources :comments_course_posts

  resources :course_posts

  resources :courses

  resources :comments_open_group_posts

  resources :open_group_posts

  resources :open_groups

  root to: 'menu#index'
  devise_for :users

  devise_for :admin_users, ActiveAdmin::Devise.config
  ActiveAdmin.routes(self)

  resources :users

  resources :open_groups do
     post :join, :on => :collection
     post :like, :on => :collection
     post :like_post, :on => :collection
     post :like_comment, :on => :collection
  end

  resources :closed_groups do
     post :join, :on => :collection
     post :like, :on => :collection
     post :like_post, :on => :collection
  end
  
  resources :courses do
     post :join, :on => :collection
     post :like, :on => :collection
     post :like_post, :on => :collection
  end

end

app/models/admin_user.rb
class AdminUser < ActiveRecord::Base
  # Include default devise modules. Others available are:
  # :confirmable, :lockable, :timeoutable and :omniauthable
  devise :database_authenticatable, 
         :recoverable, :rememberable, :trackable, :validatable

  # Setup accessible (or protected) attributes for your model
  attr_accessible :email, :password, :password_confirmation, :remember_me
  # attr_accessible :title, :body
end

app/models/closed_group.rb
class ClosedGroup < ActiveRecord::Base
  attr_accessible :admin_id, :decription, :name

  has_many :user_closed_group
  has_many :closed_group_posts
  has_many :requests
end

app/models/closed_group_post.rb
class ClosedGroupPost < ActiveRecord::Base
  attr_accessible :closed_group_id, :content, :title, :user_id, :attach

  belongs_to :user
  belongs_to :closed_group

  has_many :likes_closed_group_posts
  has_many :comments_closed_group_posts
  has_attached_file :attach
end

app/models/comments_course_post.rb
class CommentsCoursePost < ActiveRecord::Base
  attr_accessible :content, :course_post_id, :user_id

  belongs_to :user
  belongs_to :course_post
end

app/models/course.rb
class Course < ActiveRecord::Base
  attr_accessible :description, :name, :user_id

  has_many :user_courses
  has_many :course_posts
end

app/models/course_post.rb
class CoursePost < ActiveRecord::Base
  attr_accessible :content, :course_id, :title, :user_id, :attach

  belongs_to :user
  belongs_to :course

  has_many :likes_course_posts
  has_many :comments_course_posts
  has_attached_file :attach
end

app/models/likes_closed_group.rb
class LikesClosedGroup < ActiveRecord::Base
  attr_accessible :closed_group_id, :user_id

  belongs_to :user
  belongs_to :closed_group
end

app/models/likes_course.rb
class LikesCourse < ActiveRecord::Base
  attr_accessible :course_id, :user_id

  belongs_to :user
  belongs_to :course
end

app/models/likes_course_post.rb
class LikesCoursePost < ActiveRecord::Base
  attr_accessible :course_post_id, :like_attribute, :user_id
  
  belongs_to :user
  belongs_to :course_post
end

app/models/likes_open_group.rb
class LikesOpenGroup < ActiveRecord::Base
  attr_accessible :open_group_id, :user_id

  belongs_to :user
  belongs_to :open_group
end

app/models/open_group.rb
class OpenGroup < ActiveRecord::Base
  attr_accessible :description, :name

  has_many :user_open_group
  has_many :open_group_posts
end

app/models/open_group_post.rb
class OpenGroupPost < ActiveRecord::Base
  attr_accessible :content, :open_group_id, :title, :user_id, :attach

  belongs_to :user
  belongs_to :open_group

  has_many :likes_open_group_posts
  has_many :comments_open_group_posts
  has_attached_file :attach
end

app/models/quick_answer.rb
class QuickAnswer < ActiveRecord::Base
  attr_accessible :answer, :quick_question_id, :user_id

  belongs_to :quick_question
  belongs_to :user
end

app/models/quick_question.rb
class QuickQuestion < ActiveRecord::Base
  attr_accessible :question, :user_id

  belongs_to :user
  has_many :quick_answers
end

app/models/request.rb
class Request < ActiveRecord::Base
  attr_accessible :closed_group_id, :user_id

  belongs_to :closed_group
  belongs_to :user
end

app/models/user.rb
class User < ActiveRecord::Base
  # Include default devise modules. Others available are:
  # :confirmable, :lockable, :timeoutable and :omniauthable
  devise :database_authenticatable, :registerable, :recoverable, :rememberable, :trackable, :validatable

  # Setup accessible (or protected) attributes for your model
  attr_accessible :email, :password, :password_confirmation, :remember_me
  attr_accessible :email, :name, :password, :attach, :pic
  validates :name, :presence => true    
  validates :email, :presence => true

  has_attached_file :pic, :styles => { :medium => "300x300>", :thumb => "100x100>" }
  has_attached_file :attach

  has_many :user_open_group
  has_many :open_group_posts
  has_many :likes_open_groups
  has_many :likes_open_group_posts
  has_many :comments_open_group_posts

  has_many :user_course
  has_many :course_posts
  has_many :likes_courses
  has_many :likes_course_posts
  has_many :comments_course_posts

  has_many :user_closed_group
  has_many :closed_group_posts
  has_many :likes_closed_group
  has_many :likes_closed_group_posts
  has_many :comments_closed_group_posts
end

app/models/user_closed_group.rb
class UserClosedGroup < ActiveRecord::Base
  attr_accessible :closed_group_id, :user_id

  belongs_to :closed_group
  belongs_to :user
end

app/models/user_course.rb
class UserCourse < ActiveRecord::Base
  attr_accessible :course_id, :user_id

  belongs_to :course
  belongs_to :user
end

app/models/user_open_group.rb
class UserOpenGroup < ActiveRecord::Base
  attr_accessible :open_group_id, :user_id

  belongs_to :open_group
  belongs_to :user
end

app/controllers/comments_course_posts_controller.rb
class CommentsCoursePostsController < ApplicationController
  # GET /comments_course_posts
  # GET /comments_course_posts.json
  def index
    @comments_course_posts = CommentsCoursePost.all

    respond_to do |format|
      format.html # index.html.erb
      format.json { render json: @comments_course_posts }
    end
  end

  # GET /comments_course_posts/1
  # GET /comments_course_posts/1.json
  def show
    @comments_course_post = CommentsCoursePost.find(params[:id])

    respond_to do |format|
      format.html # show.html.erb
      format.json { render json: @comments_course_post }
    end
  end

  # GET /comments_course_posts/new
  # GET /comments_course_posts/new.json
  def new
    @comments_course_post = CommentsCoursePost.new

    respond_to do |format|
      format.html # new.html.erb
      format.json { render json: @comments_course_post }
    end
  end

  # GET /comments_course_posts/1/edit
  def edit
    @comments_course_post = CommentsCoursePost.find(params[:id])
  end

  # POST /comments_course_posts
  # POST /comments_course_posts.json
  def create
    @comments_course_post = CommentsCoursePost.new(params[:comments_course_post])

    respond_to do |format|
      if @comments_course_post.save
        format.html { redirect_to :back }
        format.json { render json: @comments_course_post, status: :created, location: @comments_course_post }
      else
        format.html { render action: "new" }
        format.json { render json: @comments_course_post.errors, status: :unprocessable_entity }
      end
    end
  end

  # PUT /comments_course_posts/1
  # PUT /comments_course_posts/1.json
  def update
    @comments_course_post = CommentsCoursePost.find(params[:id])

    respond_to do |format|
      if @comments_course_post.update_attributes(params[:comments_course_post])
        format.html { redirect_to @comments_course_post, notice: 'Comments course post was successfully updated.' }
        format.json { head :no_content }
      else
        format.html { render action: "edit" }
        format.json { render json: @comments_course_post.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /comments_course_posts/1
  # DELETE /comments_course_posts/1.json
  def destroy
    @comments_course_post = CommentsCoursePost.find(params[:id])
    @comments_course_post.destroy

    respond_to do |format|
      format.html { redirect_to comments_course_posts_url }
      format.json { head :no_content }
    end
  end
end

app/helpers/comments_course_posts_helper.rb
module CommentsCoursePostsHelper
end

app/helpers/courses_helper.rb
module CoursesHelper
end

app/helpers/users_helper.rb
module UsersHelper
end

app/views/comments_course_posts/_form.html.erb
<%= form_for(@comments_course_post) do |f| %>
  <% if @comments_course_post.errors.any? %>
    <div id="error_explanation">
      <h2><%= pluralize(@comments_course_post.errors.count, "error") %> prohibited this comments_course_post from being saved:</h2>

      <ul>
      <% @comments_course_post.errors.full_messages.each do |msg| %>
        <li><%= msg %></li>
      <% end %>
      </ul>
    </div>
  <% end %>

  <div class="field">
    <%= f.label :content %><br />
    <%= f.text_area :content %>
  </div>
  <div class="field">
    <%= f.label :course_post_id %><br />
    <%= f.number_field :course_post_id %>
  </div>
  <div class="field">
    <%= f.label :user_id %><br />
    <%= f.number_field :user_id %>
  </div>
  <div class="actions">
    <%= f.submit %>
  </div>
<% end %>

app/views/comments_course_posts/edit.html.erb
<h1>Editing comments_course_post</h1>

<%= render 'form' %>

<%= link_to 'Show', @comments_course_post %> |
<%= link_to 'Back', comments_course_posts_path %>

app/views/comments_course_posts/index.html.erb
<h1>Listing comments_course_posts</h1>

<table>
  <tr>
    <th>Content</th>
    <th>Course post</th>
    <th>User</th>
    <th></th>
    <th></th>
    <th></th>
  </tr>

<% @comments_course_posts.each do |comments_course_post| %>
  <tr>
    <td><%= comments_course_post.content %></td>
    <td><%= comments_course_post.course_post_id %></td>
    <td><%= comments_course_post.user_id %></td>
    <td><%= link_to 'Show', comments_course_post %></td>
    <td><%= link_to 'Edit', edit_comments_course_post_path(comments_course_post) %></td>
    <td><%= link_to 'Destroy', comments_course_post, method: :delete, data: { confirm: 'Are you sure?' } %></td>
  </tr>
<% end %>
</table>

<br />

<%= link_to 'New Comments course post', new_comments_course_post_path %>

app/views/comments_course_posts/new.html.erb
<h1>New comments_course_post</h1>

<%= render 'form' %>

<%= link_to 'Back', comments_course_posts_path %>

app/views/comments_course_posts/show.html.erb
<p id="notice"><%= notice %></p>

<p>
  <b>Content:</b>
  <%= @comments_course_post.content %>
</p>

<p>
  <b>Course post:</b>
  <%= @comments_course_post.course_post_id %>
</p>

<p>
  <b>User:</b>
  <%= @comments_course_post.user_id %>
</p>


<%= link_to 'Edit', edit_comments_course_post_path(@comments_course_post) %> |
<%= link_to 'Back', comments_course_posts_path %>